- name: Download a Build Artifact
  uses: actions/download-artifact@v3.1.0
  with:
    # Artifact name
    name: # optional
    # Destination path
    path: # optional
  push:
    branches: [ main, master ]
  workflow_dispatch:

defaults:
  run:
    working-directory: gamebox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Backup pubspec before flutter create
        run: cp pubspec.yaml pubspec.yaml.bak

      - name: Generate missing Android platform files
        run: flutter create --platforms=android --project-name=gamebox --org com.example .

      - name: Restore original pubspec
        run: mv pubspec.yaml.bak pubspec.yaml

      - name: Force Android compileSdk and targetSdk to 36
        run: |
          # Groovy (.gradle) fayllari uchun
          find android/ -type f -name "*.gradle" -exec sed -i 's/compileSdkVersion.*/compileSdkVersion 36/g' {} +
          find android/ -type f -name "*.gradle" -exec sed -i 's/targetSdkVersion.*/targetSdkVersion 36/g' {} +

          # Kotlin Script (.kts) fayllari uchun
          find android/ -type f -name "*.gradle.kts" -exec sed -i 's/compileSdk =.*/compileSdk = 36/g' {} +
          find android/ -type f -name "*.gradle.kts" -exec sed -i 's/targetSdk =.*/targetSdk = 36/g' {} +

      - name: Update pubspec.yaml to allow file_picker update
        run: |
          sed -i 's/file_picker:.*/file_picker: ^12.0.0/' pubspec.yaml || true
          flutter pub get

      - name: Generate app launcher icon
        run: dart run flutter_launcher_icons

      - name: Clean build cache
        run: flutter clean

      - name: Build release APK
        run: flutter build apk --release --build-number=${{ github.run_number }}

      - name: Rename APK with version and build number
        run: |
          mkdir -p renamed
          cp build/app/outputs/flutter-apk/app-release.apk \
             renamed/GameBox-v1.0.${{ github.run_number }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GameBox-v1.0.${{ github.run_number }}
          path: gamebox/renamed/GameBox-v1.0.${{ github.run_number }}.apk
          
